kind: pipeline
name: default

steps:
  # don't have any tests yet so just check it builds
- name: install
  image: python:3.8.0-alpine3.10
  commands:
  - cd jupyterlab_dotscience_backend && pip install -e .
  # ideally we'd use the drone plugin, but that won't work until
  # https://github.com/drone-plugins/drone-pypi/issues/23 is fixed.
- name: pypi_publish
  image: python:3.8.0-slim-buster
  when:
    event: [ tag ]
  environment:
    TWINE_USERNAME: 
      from_secret: pypi_username
    TWINE_PASSWORD: 
      from_secret: pypi_password
  commands:
    - python -m venv /tmp/venv
    - cd jupyterlab_dotscience_backend
    - /tmp/venv/bin/pip install twine setuptools wheel
    - /tmp/venv/bin/python setup.py sdist bdist_wheel
    - /tmp/venv/bin/twine upload dist/*
- name: npm
  image: plugins/npm
  when:
    event: [ tag ]
  settings:
    token:
      from_secret: npm_token
    folder: jupyterlab_dotscience
- name: slack
  image: plugins/slack
  when:
    event: [ push, pull_request ]
    status: [ success, failure ]
  depends_on:
  - install
  settings:
    webhook:
      from_secret: slack_url
    channel: ci
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
- name: slack-tag
  image: plugins/slack
  when:
    event: [ tag ]
    status: [ success, failure ]
  depends_on:
  - npm
  - pypi_publish
  settings:
    webhook:
      from_secret: slack_url
    channel: ci
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
