variables:
  RELEASE_DOCKER_REGISTRY: quay.io
  RELEASE_DOCKER_REPOSITORY: dotmesh
  CI_DOCKER_TAG: $CI_COMMIT_SHA
  CI_DOCKER_PYTHON_IMAGE: $RELEASE_DOCKER_REGISTRY/$RELEASE_DOCKER_REPOSITORY/dotscience-python3:$CI_COMMIT_SHA

stages:
  - deploy
  - trigger_docker

deploy_npm:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - npm publish jupyterlab_dotscience --tag $CI_COMMIT_TAG
  only:
    - tags

# Needs PYPI_USER and PYPI_PASSWORD set; and optionally PYPI_REPO if we're using test pypi
deploy_pypi:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - ./shipit-pypi.sh -u $PYPI_USER -p $PYPI_PASSWORD
  only:
    - tags

trigger_docker:
  stage: trigger_docker
  tags:
    - ubuntu-bionic
    - fast
  script:
    - curl -X POST -F "token=$CI_JOB_TOKEN" -F "ref=master" -F "variables[PLUGIN_TAG]=$CI_COMMIT_TAG" https://gitlab.dotmesh.com/api/v4/projects/dotmesh%2Fjupyterlab-tensorflow-sync/trigger/pipeline
  only:
    - tags