FROM python:3

# THIS DOCKERFILE IS ONLY FOR BUILDING AND RELEASING TO PYPI
RUN apt-get update && apt-get install git
RUN mkdir dsbuild
COPY .git ./dsbuild/.git
COPY ./jupyterlab_dotscience_backend/.gitattributes ./dsbuild
COPY ./jupyterlab_dotscience_backend/jupyterlab_dotscience_backend ./dsbuild/jupyterlab_dotscience_backend
COPY ./jupyterlab_dotscience_backend/setup.py ./dsbuild
COPY ./jupyterlab_dotscience_backend/README.md ./dsbuild
COPY ./jupyterlab_dotscience_backend/setup.cfg ./dsbuild
COPY ./jupyterlab_dotscience_backend/MANIFEST.in ./dsbuild
COPY ./jupyterlab_dotscience_backend/versioneer.py ./dsbuild
