variables:
  RELEASE_DOCKER_REGISTRY: quay.io
  RELEASE_DOCKER_REPOSITORY: dotmesh
  CI_DOCKER_TAG: $CI_COMMIT_SHA
  CI_DOCKER_PYTHON_IMAGE: $RELEASE_DOCKER_REGISTRY/$RELEASE_DOCKER_REPOSITORY/dotscience-python3:$CI_COMMIT_SHA

stages:
  - deploy
  - trigger_docker

deploy_npm:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - ./scripts/shipit-npm.sh $NPM_TOKEN
  only:
    - tags

# Needs PYPI_USER and PYPI_PASSWORD set; and optionally PYPI_REPO if we're using test pypi
deploy_pypi:
  stage: deploy
  tags:
    - ubuntu-bionic
    - fast
  script:
    - ./scripts/shipit-pypi.sh -u $PYPI_USER -p $PYPI_PASSWORD
  only:
    - tags
